require: 
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude: [Guardfile]

Style/Documentation:
  Exclude: 
    - config/application.rb
    - db/migrate

Layout/ArgumentAlignment: 
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

